In [1]:
import numpy as ny
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv('insurance_pre.csv')
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
indepen=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
depen=dataset[['charges']]

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indepen,depen,test_size=1/3,random_state=0)

In [7]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
grid_param={'criterion':['squared_error','friedman_mse','absolute_error','poisson'],
            'splitter':['best','random'],'max_features':['auto','sqrt','log2']}

grid=GridSearchCV(DecisionTreeRegressor(),grid_param,refit=True,verbose=3,n_jobs=-1)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning:
40 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
26 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
14 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Anaconda\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.61872332 0.58318707 0.6292142  0.50837334
        nan        nan 0.60917743 0.56566377 0.63342015 0.53439439
        nan        nan 0.60333679 0.53331098 0.62478883 0.53751737
        nan        nan 0.5745785  0.57694315 0.62158255 0.55658347]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [8]:
result=grid.cv_results_
grid_prediction=grid.predict(x_test)

from sklearn.metrics import r2_score
r=r2_score(y_test,grid_prediction)
print("The R_score value for the best parameter :",format(grid.best_params_),r)

The R_score value for the best parameter : {'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'best'} 0.7301675133064144

In [9]:
table=pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001553,0.000170,0.000000,0.000000,squared_error,auto,best,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.001193,0.000026,0.000000,0.000000,squared_error,auto,random,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.006279,0.000407,0.005535,0.004493,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.669718,0.611425,0.658038,0.624166,0.530270,0.618723,0.049098,5
3,0.004920,0.000085,0.005131,0.003946,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.724273,0.448240,0.504915,0.688856,0.549651,0.583187,0.106332,8
4,0.006329,0.000420,0.003114,0.000114,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.724601,0.597488,0.729824,0.667273,0.426885,0.629214,0.111904,2
5,0.005319,0.000547,0.003186,0.000182,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.484751,0.445717,0.698427,0.478874,0.434098,0.508373,0.096945,16
6,0.001224,0.000060,0.000000,0.000000,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
7,0.001240,0.000124,0.000000,0.000000,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,0.005861,0.000406,0.003167,0.000051,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.611113,0.498188,0.678784,0.620571,0.637231,0.609177,0.060141,6
9,0.005113,0.000274,0.003080,0.000044,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.560396,0.496697,0.696468,0.526393,0.548365,0.565664,0.068899,11
10,0.005887,0.000461,0.003636,0.000466,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.647173,0.594201,0.642684,0.685846,0.597197,0.633420,0.034274,1
11,0.006140,0.001296,0.003627,0.000695,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.519605,0.552635,0.639473,0.403879,0.556380,0.534394,0.076303,14
12,0.001289,0.000181,0.000000,0.000000,absolute_error,auto,best,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
13,0.004239,0.006152,0.000000,0.000000,absolute_error,auto,random,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
14,0.014873,0.002626,0.003328,0.000119,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.615053,0.668221,0.644734,0.603694,0.484982,0.603337,0.063354,7
15,0.010817,0.000608,0.003297,0.000148,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.680880,0.523530,0.550581,0.565865,0.345699,0.533311,0.108101,15
16,0.016256,0.005378,0.003477,0.000212,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.645477,0.639860,0.637065,0.599487,0.602055,0.624789,0.019814,3
17,0.010626,0.000647,0.003325,0.000299,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.392087,0.601887,0.571709,0.551590,0.570314,0.537517,0.074480,13
18,0.001166,0.000028,0.000000,0.000000,poisson,auto,best,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.001201,0.000032,0.000000,0.000000,poisson,auto,random,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
20,0.006329,0.000385,0.005099,0.003501,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.633314,0.271431,0.627195,0.674309,0.666643,0.574579,0.152669,10
21,0.005483,0.000324,0.003293,0.000121,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.529211,0.660597,0.630893,0.513477,0.550537,0.576943,0.058159,9
22,0.006665,0.000281,0.003407,0.000351,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.661162,0.564483,0.705413,0.555061,0.621793,0.621583,0.057061,4
23,0.005499,0.000639,0.003186,0.000108,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.510393,0.607557,0.519534,0.536091,0.609342,0.556583,0.043146,12