In [1]:
import numpy as ny
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv('insurance_pre.csv')
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
indepen=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
depen=dataset[['charges']]

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indepen,depen,test_size=1/3,random_state=0)

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
grid_prameters={'kernel':['rbf','sigmoid','linear'],'C':[1,10,100,1000,2000],
                'gamma':['auto','scale']}

grid=GridSearchCV(SVR(),grid_prameters,refit=True,verbose=3,n_jobs=-1)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

C:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [1, 10, 100, 1000, 2000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'sigmoid', 'linear']},
             verbose=3)

In [11]:
result=grid.cv_results_
grid_prediction=grid.predict(x_test)

from sklearn.metrics import r2_score
r=r2_score(y_test,grid_prediction)
print("The R_score value for the best parameter :",format(grid.best_params_),r)

The R_score value for the best parameter : {'C': 2000, 'gamma': 'auto', 'kernel': 'linear'} 0.6253680212857904

In [12]:
table=pd.DataFrame.from_dict(result)
table

    mean_fit_time  std_fit_time  mean_score_time  ...  mean_test_score  std_test_score rank_test_score
0        0.047176      0.003562         0.018888  ...        -0.100446        0.052465              15
1        0.027706      0.003292         0.006824  ...        -0.100475        0.052495              16
2        0.035372      0.002994         0.006134  ...        -0.145590        0.092979              24
3        0.037745      0.001625         0.018338  ...        -0.099981        0.053599              14
4        0.044444      0.000603         0.011198  ...        -0.100584        0.052433              21
5        0.033349      0.003640         0.006379  ...        -0.145590        0.092979              24
6        0.043992      0.002255         0.018324  ...        -0.099788        0.052820              13
7        0.026973      0.000965         0.006671  ...        -0.100475        0.052495              16
8        0.038046      0.003295         0.006721  ...        -0.057260        0.087808               8
9        0.035037      0.000981         0.017925  ...        -0.097516        0.062647              12
10       0.044315      0.000948         0.010996  ...        -0.102067        0.052442              22
11       0.037891      0.001650         0.006160  ...        -0.057260        0.087808               8
12       0.042064      0.000747         0.018029  ...        -0.091595        0.056486              11
13       0.025922      0.000522         0.006621  ...        -0.100475        0.052495              16
14       0.075498      0.009419         0.006137  ...         0.474756        0.047502               5
15       0.035477      0.001578         0.018761  ...        -0.146979        0.092427              26
16       0.044201      0.000983         0.011348  ...        -0.118441        0.048296              23
17       0.078112      0.002976         0.005904  ...         0.474756        0.047502               5
18       0.059106      0.001184         0.017688  ...        -0.087029        0.081135              10
19       0.025168      0.000497         0.006654  ...        -0.100475        0.052495              16
20       0.398184      0.088353         0.006010  ...         0.591434        0.030141               3
21       0.041081      0.002725         0.017725  ...        -0.154902        0.094927              28
22       0.045844      0.001154         0.010786  ...        -1.112664        0.098750              29
23       0.388647      0.084939         0.006140  ...         0.591434        0.030141               3
24       0.074733      0.002210         0.018257  ...        -0.055871        0.084797               7
25       0.026412      0.000621         0.006906  ...        -0.100475        0.052495              16
26       0.642415      0.111330         0.007905  ...         0.611564        0.046661               1
27       0.042918      0.001289         0.018738  ...        -0.147751        0.096028              27
28       0.045547      0.000636         0.011388  ...        -3.856898        0.502677              30
29       0.579197      0.104457         0.006505  ...         0.611564        0.046661               1

[30 rows x 16 columns]