In [1]:
import numpy as ny
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv('insurance_pre.csv')
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
indepen=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
depen=dataset[['charges']]

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indepen,depen,test_size=1/3,random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [8]:
scy=StandardScaler()
y_train=scy.fit_transform(y_train)
y_test=scy.transform(y_test)

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
grid_param={'criterion':['squared_error','friedman_mse','absolute_error','poisson'],
            'splitter':['best','random'],'max_features':['auto','sqrt','log2']}

grid=GridSearchCV(DecisionTreeRegressor(),grid_param,refit=True,verbose=3,n_jobs=-1)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning:
60 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Anaconda\Lib\site-packages\sklearn\tree\_classes.py", line 1404, in fit
    super()._fit(
    ~~~~~~~~~~~~^
        X,
        ^^
    ...<2 lines>...
        check_input=check_input,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda\Lib\site-packages\sklearn\tree\_classes.py", line 269, in _fit
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Some value(s) of y are negative which is not allowed for Poisson regression.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Anaconda\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.61305213 0.58046852 0.60750742 0.59722912
        nan        nan 0.61023648 0.55751996 0.63894854 0.55524187
        nan        nan 0.60408725 0.59430041 0.56684997 0.56027487
        nan        nan        nan        nan        nan        nan]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [11]:
result=grid.cv_results_
grid_prediction=grid.predict(x_test)

from sklearn.metrics import r2_score
r=r2_score(y_test,grid_prediction)
print('The R_score value for best parameters :',format(grid.best_params_),r)

The R_score value for best parameters : {'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'best'} 0.676851372601731

In [12]:
table=pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000466,0.000078,0.000000,0.000000,squared_error,auto,best,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
1,0.000477,0.000179,0.000000,0.000000,squared_error,auto,random,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
2,0.002817,0.000384,0.001168,0.000132,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.452973,0.543781,0.728873,0.710956,0.628677,0.613052,0.103603,2
3,0.002083,0.000139,0.001100,0.000087,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.622617,0.624506,0.394127,0.617649,0.643443,0.580469,0.093581,8
4,0.003294,0.000168,0.001461,0.000363,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.623197,0.542692,0.674513,0.516074,0.681062,0.607507,0.067390,4
5,0.002329,0.000408,0.001245,0.000169,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.627928,0.555128,0.639174,0.604063,0.559853,0.597229,0.034403,6
6,0.000502,0.000129,0.000000,0.000000,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
7,0.000369,0.000033,0.000000,0.000000,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
8,0.002859,0.000319,0.001056,0.000030,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.578077,0.651324,0.609676,0.638679,0.573427,0.610236,0.031263,3
9,0.002228,0.000375,0.001235,0.000367,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.669701,0.509396,0.664039,0.479760,0.464703,0.557520,0.090453,11
10,0.002833,0.000287,0.001015,0.000025,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.647502,0.444289,0.728236,0.744261,0.630455,0.638949,0.106865,1
11,0.002186,0.000335,0.001126,0.000074,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.550530,0.569858,0.578473,0.504730,0.572619,0.555242,0.026940,12
12,0.000468,0.000148,0.000000,0.000000,absolute_error,auto,best,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
13,0.000463,0.000217,0.000000,0.000000,absolute_error,auto,random,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
14,0.011194,0.001807,0.001038,0.000041,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.566527,0.507555,0.718320,0.673505,0.554530,0.604087,0.078808,5
15,0.007519,0.000943,0.002673,0.003129,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.611742,0.607625,0.654579,0.593531,0.504024,0.594300,0.049529,7
16,0.010840,0.001719,0.001087,0.000135,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.677963,0.612266,0.454332,0.465547,0.624142,0.566850,0.090126,9
17,0.007723,0.000738,0.001015,0.000035,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.581421,0.534629,0.582048,0.507159,0.596117,0.560275,0.033719,10
18,0.000337,0.000018,0.000000,0.000000,poisson,auto,best,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
19,0.000331,0.000037,0.000000,0.000000,poisson,auto,random,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
20,0.000752,0.000074,0.000000,0.000000,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
21,0.000661,0.000031,0.000000,0.000000,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
22,0.000807,0.000224,0.000000,0.000000,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
23,0.000821,0.000232,0.000000,0.000000,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13

In [13]:
import pickle

In [14]:
filename="finalized_model_DR.sav"
pickle.dump(grid,open(filename,'wb'))

In [17]:
preinput_data=[[25,33.5,3,1,0]]

In [18]:
preinput=sc.transform(preinput_data)

C:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [19]:
preinput

array([[-1.03919296,  0.45834558,  1.58903774,  1.01127431, -0.49929923]])

In [21]:
load_model=pickle.load(open("finalized_model_DR.sav",'rb'))
result=load_model.predict(preinput)

In [22]:
result

array([-0.717481])

In [24]:
preoutput=scy.inverse_transform([result])
preoutput

array([[4661.28635]])